spring:
  application:
    name: flyapi-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flyapi
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session
  session:
    timeout: 86400
    store-type: redis
  # redis
  redis:
    port: 6379
    host: localhost
    database: 3
  mail:
    host: smtp.qq.com
    port: 25
    username: flycodeu@qq.com
    password: bcvbqwtpurzlddgj


server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #
      logic-delete-value: 1 #
      logic-not-delete-value: 0 #

#flyapi:
#  client:
#    access-key: 9e44946a265c996e05f6fad5bab87249
#    secret-key: 4440120741c2ba54361754056a1c134e


dubbo:
  application:
    name: dubbo-api-platform-backend-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

flyapi:
  client:
    assess-key: ef0d10633892b45daec60881f8f86c42
    secret-key: b61ac354d62dd873b60e8b39b1505000


